### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by ccc0917** [taishan1994/BERT-BILSTM-CRF#1]
Traceback (most recent call last):
  File "D:\python\python-workspace\BERT-BILSTM-CRF\main.py", line 189, in <module>
    main(data_name)
  File "D:\python\python-workspace\BERT-BILSTM-CRF\main.py", line 159, in main
    model = BertNer(args)
  File "D:\python\python-workspace\BERT-BILSTM-CRF\model.py", line 25, in __init__
    self.crf = CRF(args.num_labels, batch_first=True)
TypeError: __init__() got an unexpected keyword argument 'batch_first'
大佬们，这个是什么问题呢？怎么解决啊

**Comment by taishan1994** [comment]
> Traceback (most recent call last): File "D:\python\python-workspace\BERT-BILSTM-CRF\main.py", line 189, in main(data_name) File "D:\python\python-workspace\BERT-BILSTM-CRF\main.py", line 159, in main model = BertNer(args) File "D:\python\python-workspace\BERT-BILSTM-CRF\model.py", line 25, in **init** self.crf = CRF(args.num_labels, batch_first=True) TypeError: **init**() got an unexpected keyword argument 'batch_first' 大佬们，这个是什么问题呢？怎么解决啊

pip install pytorch-crf==0.7.2
