### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by dongyuanHe** [taishan1994/BERT-BILSTM-CRF#12]
['O', 'B-故障设备', 'I-故障设备', 'B-故障原因', 'I-故障原因']
{'O': 0, 'B-故障设备': 1, 'I-故障设备': 2, 'B-故障原因': 3, 'I-故障原因': 4}
Some weights of the model checkpoint at ./model_hub/chinese-bert-wwm-ext/ were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
F:\Program Files\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\rnn.py:62: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "
Traceback (most recent call last):
  File "e:\硕士毕业\BERT-BLSTM-CRF\ner\main.py", line 189, in <module>
    main(data_name)
  File "e:\硕士毕业\BERT-BLSTM-CRF\ner\main.py", line 159, in main
    model = BertNer(args)
  File "e:\硕士毕业\BERT-BLSTM-CRF\ner\model.py", line 24, in __init__
    self.crf = CRF(args.num_labels, batch_first=True)
TypeError: __init__() got an unexpected keyword argument 'batch_first'
大佬请问能看一下报错原因吗

**Comment by taishan1994** [comment]
pip install pytorch-crf==0.7.2

**Comment by dongyuanHe** [comment]
> pip install pytorch-crf==0.7.2

佬，为啥我安装了pytorch-crf==0.7.2，还是这样的报错

**Comment by taishan1994** [comment]
可以先看下目前已安装的版本，然后先把它删除掉，再进行安装。

**Comment by dongyuanHe** [comment]
> 可以先看下目前已安装的版本，然后先把它删除掉，再进行安装。

运行成功了，但是loss都是几十，正常吗？

**Comment by taishan1994** [comment]
> > 可以先看下目前已安装的版本，然后先把它删除掉，再进行安装。
> 
> 运行成功了，但是loss都是几十，正常吗？

多训练会就会下降的。

**Comment by dongyuanHe** [comment]
> > > 可以先看下目前已安装的版本，然后先把它删除掉，再进行安装。
> > 
> > 
> > 运行成功了，但是loss都是几十，正常吗？
> 
> 多训练会就会下降的。

佬，意思是多加几个epoch吗

**Comment by taishan1994** [comment]
是的

**Comment by dongyuanHe** [comment]
> 是的

佬，4080的话，设置多少个epoch好呢

**Comment by taishan1994** [comment]
看数据量，自己可以多试试几个。

**Comment by dongyuanHe** [comment]
> 看数据量，自己可以多试试几个。

数据集差不多是一万条文本

**Comment by kejiakebujia** [comment]
> 可以先看下目前已安装的版本，然后先把它删除掉，再进行安装。

你好大佬，我这样照做为什么还是报错
