### ISSUE TITLE
运行时报错  求助佬

### ISSUE THREAD

**Issue by yintelaixi** [taishan1994/BERT-BILSTM-CRF#22]
['O', 'B-故障设备', 'I-故障设备', 'B-故障原因', 'I-故障原因']
{'O': 0, 'B-故障设备': 1, 'I-故障设备': 2, 'B-故障原因': 3, 'I-故障原因': 4}
Some weights of the model checkpoint at ./model_hub/chinese-bert-wwm-ext/ were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\rnn.py:62: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "
C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
Traceback (most recent call last):
  File "C:/Users/DELL/Desktop/BERT-BILSTM-CRF-main/main.py", line 190, in <module>
    main(data_name)
  File "C:/Users/DELL/Desktop/BERT-BILSTM-CRF-main/main.py", line 182, in main
    train.train()
  File "C:/Users/DELL/Desktop/BERT-BILSTM-CRF-main/main.py", line 52, in train
    output = self.model(input_ids, attention_mask, labels)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\DELL\Desktop\BERT-BILSTM-CRF-main\model.py", line 36, in forward
    loss = -self.crf(seq_out, labels, mask=attention_mask.bool(), reduction='mean')
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\TorchCRF\__init__.py", line 102, in forward
    numerator = self._compute_score(emissions, tags, mask)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\site-packages\TorchCRF\__init__.py", line 186, in _compute_score
    score = self.start_transitions[tags[0]]
**IndexError: tensors used as indices must be long, byte or bool tensors**

Process finished with exit code 1

**Comment by taishan1994** [comment]
torch版本的问题。

**Comment by yintelaixi** [comment]
谢谢佬

**Comment by wendy-baby** [comment]
torch 版本是1.13.1，也出现这个问题啊，最后怎么解决的

**Comment by Henry-Matchless** [comment]
好像分别在main.py和model.py加上这两个就解决了
![image](https://github.com/user-attachments/assets/61059b17-5273-4fe9-b670-d6de4bb8eb75)
![image](https://github.com/user-attachments/assets/efe99d10-4ff6-48e1-92c3-51ca199866f5)
