### ISSUE TITLE
求助，在跑源码时报错，这个怎么解决啊，显示的是IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by wendy-baby** [taishan1994/BERT-BILSTM-CRF#30]
D:\anaconda3\lib\site-packages\transformers\optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
Traceback (most recent call last):
  File "D:\小月\BERT-BILSTM-CRF-main\BERT-BILSTM-CRF-main\main.py", line 191, in <module>
    main(data_name)
  File "D:\小月\BERT-BILSTM-CRF-main\BERT-BILSTM-CRF-main\main.py", line 183, in main
    train.train()
  File "D:\小月\BERT-BILSTM-CRF-main\BERT-BILSTM-CRF-main\main.py", line 53, in train
    output = self.model(input_ids, attention_mask, labels)
  File "D:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\小月\BERT-BILSTM-CRF-main\BERT-BILSTM-CRF-main\model.py", line 38, in forward
    loss = -self.crf(seq_out, labels, mask=attention_mask.bool(), reduction='mean')
  File "D:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\anaconda3\lib\site-packages\torchcrf\__init__.py", line 102, in forward
    numerator = self._compute_score(emissions, tags, mask)
  File "D:\anaconda3\lib\site-packages\torchcrf\__init__.py", line 186, in _compute_score
    score = self.start_transitions[tags[0]]
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by Oliver-Queen-Liu** [comment]
你好，我也遇到了这个问题，请问你是怎么解决的啊？谢谢！
