### ISSUE TITLE
数据格式问题

### ISSUE THREAD

**Issue by ygwangg** [taishan1994/BERT-BILSTM-CRF#33]
大佬您好
我使用我自己的数据后报错：
C:\Users\someb\.conda\envs\49\python.exe "D:\NER\BERT-BILSTM-CRF-main - 副本\main.py" 
['O', 'B-地名', 'I-地名', 'B-潜在污染物', 'I-潜在污染物', 'B-土壤性质', 'I-土壤性质', 'B-植物', 'I-植物', 'B-气候条件', 'I-气候条件', 'B-土地使用类型', 'I-土地使用类型', 'B-矿名', 'I-矿名']
{'O': 0, 'B-地名': 1, 'I-地名': 2, 'B-潜在污染物': 3, 'I-潜在污染物': 4, 'B-土壤性质': 5, 'I-土壤性质': 6, 'B-植物': 7, 'I-植物': 8, 'B-气候条件': 9, 'I-气候条件': 10, 'B-土地使用类型': 11, 'I-土地使用类型': 12, 'B-矿名': 13, 'I-矿名': 14}
Traceback (most recent call last):
  File "D:\NER\BERT-BILSTM-CRF-main - 副本\main.py", line 196, in <module>
    main(data_name)
  File "D:\NER\BERT-BILSTM-CRF-main - 副本\main.py", line 154, in main
    train_data = [json.loads(d) for d in train_data]
  File "D:\NER\BERT-BILSTM-CRF-main - 副本\main.py", line 154, in <listcomp>
    train_data = [json.loads(d) for d in train_data]
  File "C:\Users\someb\.conda\envs\49\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\someb\.conda\envs\49\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\someb\.conda\envs\49\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 277 (char 276)
我检查了一下我的数据发现并没有问题：
{"id": "1000", "text": ["研", "究", "区", "位", "于", "贵", "州", "省", "水", "城", "县", "境", "内", "，", "属", "亚", "热", "带", "高", "原", "型", "季", "风", "气", "候", "区", "。", "区", "内", "主", "要", "有", "煤", "、", "铅", "、", "锌", "、", "硫", "铁", "、", "硅", "石", "等", "矿", "产", "。", "本", "次", "研", "究", "选", "取", "的", "矿", "区", "分", "别", "为", "水", "城", "县", "的", "凉", "山", "村", "玉", "兰", "、", "茨", "冲", "村", "永", "昌", "、", "仁", "活", "洞", "村", "杉", "树", "林", "铅", "锌", "矿", "。", "其", "中", ",", "玉", "兰", "和", "永", "昌", "为", "废", "弃", "矿", "山", ",", "杉", "树", "林", "是", "正", "在", "生", "产", "的", "矿", "山", "。"], "labels": ["O", "O", "O", "O", "O", "B-地名", "I-地名", "I-地名", "B-地名", "I-地名", "I-地名", "O", "O", "O", "O", "B-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "O", "B-潜在污染物", "O", "B-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "I-地名", "O", "B-地名", "I-地名", "I-地名", "O", "O", "O", "B-地名", "I-地名", "I-地名", "O", "O", "O", "B-地名", "I-地名", "I-地名", "I-地名", "O", "O", "O", "B-矿名", "I-矿名", "I-矿名", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-土地使用类型", "I-土地使用类型", "I-土地使用类型", "I-土地使用类型", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-土地使用类型", "I-土地使用类型", "O"]}
{"id": "1002", "text": ["研", "究", "区", "重", "金", "属", "含", "量", "与", "贵", "州", "省", "土", "壤", "背", "景", "值", "相", "比", ",", "超", "标", "率", "从", "大", "至", "小", "为", ":", "C", "d", "(", "1", "0", "0", "%", ")", "=", "Z", "n", "(", "1", "0", "0", "%", ")", ">", "P", "b", "(", "9", "3", ".", "9", "4", "%", ")", ">", "C", "u", "(", "8", "7", ".", "8", "8", "%", ")", ">", "H", "g", "(", "7", "8", ".", "7", "9", "%", ")", ">", "N", "i", "(", "6", "6", ".", "6", "7", "%", ")", ">", "A", "s", "(", "5", "4", ".", "5", "5", "%", ")", ">", "C", "r", "(", "4", "5", ".", "4", "5", "%", ")", "。", "其", "中", ",", "玉", "兰", "和", "永", "昌", "矿", "区", "P", "b", "、", "Z", "n", "、", "C", "d", "和", "C", "u", ",", "杉", "树", "林", "矿", "区", "P", "b", "、", "Z", "n", "、", "C", "d", "、", "H", "g", "和", "A", "s", "属", "重", "度", "污", "染", ",", "其", "余", "为", "轻", "度", "污", "染", "或", "清", "洁", "状", "态", "。", "综", "合", "污", "染", "指", "数", "依", "次", "为", ":", "杉", "树", "林", "(", "4", "1", ".", "3", "7", ")", ">", "玉", "兰", "(", "1", "5", ".", "8", "1", ")", ">", "永", "昌", "(", "1", "0", ".", "0", "5", ")", ",", "均", "属", "重", "度", "污", "染", "。"], "labels": ["O", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "I-地名", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "O", "B-地名", "I-地名", "B-土地使用类型", "I-土地使用类型", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "B-地名", "I-地名", "I-地名", "B-土地使用类型", "I-土地使用类型", "B-潜在污染物", "I-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "I-地名", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}
上面是我的数据的第一条和第二条，
请问还是数据有问题吗

**Comment by taishan1994** [comment]
吧json.load(d)换成eval(d)试试。

**Comment by sore-2001** [comment]
> 大佬您好 我使用我自己的数据后报错： C:\Users\someb.conda\envs\49\python.exe "D:\NER\BERT-BILSTM-CRF-main - 副本\main.py" ['O', 'B-地名', 'I-地名', 'B-潜在污染物', 'I-潜在污染物', 'B-土壤性质', 'I-土壤性质', 'B-植物', 'I-植物', 'B-气候条件', 'I-气候条件', 'B-土地使用类型', 'I-土地使用类型', 'B-矿名', 'I-矿名'] {'O': 0, 'B-地名': 1, 'I-地名': 2, 'B-潜在污染物': 3, 'I-潜在污染物': 4, 'B-土壤性质': 5, 'I-土壤性质': 6, 'B-植物': 7, 'I-植物': 8, 'B-气候条件': 9, 'I-气候条件': 10, 'B-土地使用类型': 11, 'I-土地使用类型': 12, 'B-矿名': 13, 'I-矿名': 14} Traceback (most recent call last): File "D:\NER\BERT-BILSTM-CRF-main - 副本\main.py", line 196, in main(data_name) File "D:\NER\BERT-BILSTM-CRF-main - 副本\main.py", line 154, in main train_data = [json.loads(d) for d in train_data] File "D:\NER\BERT-BILSTM-CRF-main - 副本\main.py", line 154, in train_data = [json.loads(d) for d in train_data] File "C:\Users\someb.conda\envs\49\lib\json__init__.py", line 357, in loads return _default_decoder.decode(s) File "C:\Users\someb.conda\envs\49\lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "C:\Users\someb.conda\envs\49\lib\json\decoder.py", line 353, in raw_decode obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 277 (char 276) 我检查了一下我的数据发现并没有问题： {"id": "1000", "text": ["研", "究", "区", "位", "于", "贵", "州", "省", "水", "城", "县", "境", "内", "，", "属", "亚", "热", "带", "高", "原", "型", "季", "风", "气", "候", "区", "。", "区", "内", "主", "要", "有", "煤", "、", "铅", "、", "锌", "、", "硫", "铁", "、", "硅", "石", "等", "矿", "产", "。", "本", "次", "研", "究", "选", "取", "的", "矿", "区", "分", "别", "为", "水", "城", "县", "的", "凉", "山", "村", "玉", "兰", "、", "茨", "冲", "村", "永", "昌", "、", "仁", "活", "洞", "村", "杉", "树", "林", "铅", "锌", "矿", "。", "其", "中", ",", "玉", "兰", "和", "永", "昌", "为", "废", "弃", "矿", "山", ",", "杉", "树", "林", "是", "正", "在", "生", "产", "的", "矿", "山", "。"], "labels": ["O", "O", "O", "O", "O", "B-地名", "I-地名", "I-地名", "B-地名", "I-地名", "I-地名", "O", "O", "O", "O", "B-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "O", "B-潜在污染物", "O", "B-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "I-地名", "O", "B-地名", "I-地名", "I-地名", "O", "O", "O", "B-地名", "I-地名", "I-地名", "O", "O", "O", "B-地名", "I-地名", "I-地名", "I-地名", "O", "O", "O", "B-矿名", "I-矿名", "I-矿名", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-土地使用类型", "I-土地使用类型", "I-土地使用类型", "I-土地使用类型", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-土地使用类型", "I-土地使用类型", "O"]} {"id": "1002", "text": ["研", "究", "区", "重", "金", "属", "含", "量", "与", "贵", "州", "省", "土", "壤", "背", "景", "值", "相", "比", ",", "超", "标", "率", "从", "大", "至", "小", "为", ":", "C", "d", "(", "1", "0", "0", "%", ")", "=", "Z", "n", "(", "1", "0", "0", "%", ")", ">", "P", "b", "(", "9", "3", ".", "9", "4", "%", ")", ">", "C", "u", "(", "8", "7", ".", "8", "8", "%", ")", ">", "H", "g", "(", "7", "8", ".", "7", "9", "%", ")", ">", "N", "i", "(", "6", "6", ".", "6", "7", "%", ")", ">", "A", "s", "(", "5", "4", ".", "5", "5", "%", ")", ">", "C", "r", "(", "4", "5", ".", "4", "5", "%", ")", "。", "其", "中", ",", "玉", "兰", "和", "永", "昌", "矿", "区", "P", "b", "、", "Z", "n", "、", "C", "d", "和", "C", "u", ",", "杉", "树", "林", "矿", "区", "P", "b", "、", "Z", "n", "、", "C", "d", "、", "H", "g", "和", "A", "s", "属", "重", "度", "污", "染", ",", "其", "余", "为", "轻", "度", "污", "染", "或", "清", "洁", "状", "态", "。", "综", "合", "污", "染", "指", "数", "依", "次", "为", ":", "杉", "树", "林", "(", "4", "1", ".", "3", "7", ")", ">", "玉", "兰", "(", "1", "5", ".", "8", "1", ")", ">", "永", "昌", "(", "1", "0", ".", "0", "5", ")", ",", "均", "属", "重", "度", "污", "染", "。"], "labels": ["O", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "I-地名", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "O", "B-地名", "I-地名", "B-土地使用类型", "I-土地使用类型", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "B-地名", "I-地名", "I-地名", "B-土地使用类型", "I-土地使用类型", "B-潜在污染物", "I-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "I-地名", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]} 上面是我的数据的第一条和第二条， 请问还是数据有问题吗

您好，我也遇到了同样的问题，显示数据中缺乏’ ,‘ 请问您解决了吗

**Comment by lxbupt** [comment]
> > 大佬您好 我使用我自己的数据后报错： C:\Users\someb.conda\envs\49\python.exe "D:\NER\BERT-BILSTM-CRF-main - 副本\main.py" ['O', 'B-地名', 'I-地名', 'B-潜在污染物', 'I-潜在污染物', 'B-土壤性质', 'I-土壤性质', 'B-植物', 'I-植物', 'B-气候条件', 'I-气候条件', 'B-土地使用类型', 'I-土地使用类型', 'B-矿名', 'I-矿名'] {'O': 0, 'B-地名': 1, 'I-地名': 2, 'B-潜在污染物': 3, 'I-潜在污染物': 4, 'B-土壤性质': 5, 'I-土壤性质': 6, 'B-植物': 7, 'I-植物': 8, 'B-气候条件': 9, 'I-气候条件': 10, 'B-土地使用类型': 11, 'I-土地使用类型': 12, 'B-矿名': 13, 'I-矿名': 14} Traceback (most recent call last): File "D:\NER\BERT-BILSTM-CRF-main - 副本\main.py", line 196, in main(data_name) File "D:\NER\BERT-BILSTM-CRF-main - 副本\main.py", line 154, in main train_data = [json.loads(d) for d in train_data] File "D:\NER\BERT-BILSTM-CRF-main - 副本\main.py", line 154, in train_data = [json.loads(d) for d in train_data] File "C:\Users\someb.conda\envs\49\lib\json__init__.py", line 357, in loads return _default_decoder.decode(s) File "C:\Users\someb.conda\envs\49\lib\json\decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "C:\Users\someb.conda\envs\49\lib\json\decoder.py", line 353, in raw_decode obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 277 (char 276) 我检查了一下我的数据发现并没有问题： {"id": "1000", "text": ["研", "究", "区", "位", "于", "贵", "州", "省", "水", "城", "县", "境", "内", "，", "属", "亚", "热", "带", "高", "原", "型", "季", "风", "气", "候", "区", "。", "区", "内", "主", "要", "有", "煤", "、", "铅", "、", "锌", "、", "硫", "铁", "、", "硅", "石", "等", "矿", "产", "。", "本", "次", "研", "究", "选", "取", "的", "矿", "区", "分", "别", "为", "水", "城", "县", "的", "凉", "山", "村", "玉", "兰", "、", "茨", "冲", "村", "永", "昌", "、", "仁", "活", "洞", "村", "杉", "树", "林", "铅", "锌", "矿", "。", "其", "中", ",", "玉", "兰", "和", "永", "昌", "为", "废", "弃", "矿", "山", ",", "杉", "树", "林", "是", "正", "在", "生", "产", "的", "矿", "山", "。"], "labels": ["O", "O", "O", "O", "O", "B-地名", "I-地名", "I-地名", "B-地名", "I-地名", "I-地名", "O", "O", "O", "O", "B-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "I-气候条件", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "O", "B-潜在污染物", "O", "B-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "I-地名", "O", "B-地名", "I-地名", "I-地名", "O", "O", "O", "B-地名", "I-地名", "I-地名", "O", "O", "O", "B-地名", "I-地名", "I-地名", "I-地名", "O", "O", "O", "B-矿名", "I-矿名", "I-矿名", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-土地使用类型", "I-土地使用类型", "I-土地使用类型", "I-土地使用类型", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-土地使用类型", "I-土地使用类型", "O"]} {"id": "1002", "text": ["研", "究", "区", "重", "金", "属", "含", "量", "与", "贵", "州", "省", "土", "壤", "背", "景", "值", "相", "比", ",", "超", "标", "率", "从", "大", "至", "小", "为", ":", "C", "d", "(", "1", "0", "0", "%", ")", "=", "Z", "n", "(", "1", "0", "0", "%", ")", ">", "P", "b", "(", "9", "3", ".", "9", "4", "%", ")", ">", "C", "u", "(", "8", "7", ".", "8", "8", "%", ")", ">", "H", "g", "(", "7", "8", ".", "7", "9", "%", ")", ">", "N", "i", "(", "6", "6", ".", "6", "7", "%", ")", ">", "A", "s", "(", "5", "4", ".", "5", "5", "%", ")", ">", "C", "r", "(", "4", "5", ".", "4", "5", "%", ")", "。", "其", "中", ",", "玉", "兰", "和", "永", "昌", "矿", "区", "P", "b", "、", "Z", "n", "、", "C", "d", "和", "C", "u", ",", "杉", "树", "林", "矿", "区", "P", "b", "、", "Z", "n", "、", "C", "d", "、", "H", "g", "和", "A", "s", "属", "重", "度", "污", "染", ",", "其", "余", "为", "轻", "度", "污", "染", "或", "清", "洁", "状", "态", "。", "综", "合", "污", "染", "指", "数", "依", "次", "为", ":", "杉", "树", "林", "(", "4", "1", ".", "3", "7", ")", ">", "玉", "兰", "(", "1", "5", ".", "8", "1", ")", ">", "永", "昌", "(", "1", "0", ".", "0", "5", ")", ",", "均", "属", "重", "度", "污", "染", "。"], "labels": ["O", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "I-地名", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "O", "B-地名", "I-地名", "B-土地使用类型", "I-土地使用类型", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-潜在污染物", "I-潜在污染物", "O", "B-地名", "I-地名", "I-地名", "B-土地使用类型", "I-土地使用类型", "B-潜在污染物", "I-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "B-潜在污染物", "I-潜在污染物", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "I-地名", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "O", "O", "O", "O", "O", "O", "O", "O", "B-地名", "I-地名", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]} 上面是我的数据的第一条和第二条， 请问还是数据有问题吗
> 
> 您好，我也遇到了同样的问题，显示数据中缺乏’ ,‘ 请问您解决了吗

俺也一样:(
