### ISSUE TITLE
数据格式问题

### ISSUE THREAD

**Issue by lxbupt** [taishan1994/BERT-BILSTM-CRF#40]
大佬，我换成自己的数据以后运行报错
/usr/local/miniconda3/bin/python3 /hy-tmp/test/main.py 
['O', 'B-dis', 'I-dis', 'B-pro', 'I-pro', 'B-equ', 'I-equ', 'B-dru', 'I-dru', 'B-ite', 'I-ite', 'B-bod', 'I-bod', 'B-dep', 'I-dep', 'B-mic', 'I-mic']
{'O': 0, 'B-dis': 1, 'I-dis': 2, 'B-pro': 3, 'I-pro': 4, 'B-equ': 5, 'I-equ': 6, 'B-dru': 7, 'I-dru': 8, 'B-ite': 9, 'I-ite': 10, 'B-bod': 11, 'I-bod': 12, 'B-dep': 13, 'I-dep': 14, 'B-mic': 15, 'I-mic': 16}
Traceback (most recent call last):
  File "/hy-tmp/test/main.py", line 193, in <module>
    main(data_name)
  File "/hy-tmp/test/main.py", line 149, in main
    train_data = [json.loads(d) for d in train_data]
  File "/hy-tmp/test/main.py", line 149, in <listcomp>
    train_data = [json.loads(d) for d in train_data]
  File "/usr/local/miniconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/miniconda3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/miniconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
是我的数据的问题吗，这是我的数据示例
{"id": "AT0001", "text": ["（", "5", "）", "房", "室", "结", "消", "融", "和", "起", "搏", "器", "植", "入", "作", "为", "反", "复", "发", "作", "或", "难", "治", "性", "心", "房", "内", "折", "返", "性", "心", "动", "过", "速", "的", "替", "代", "疗", "法", "。"], "labels": ["O", "O", "O", "B-pro", "I-pro", "I-pro", "I-pro", "I-pro", "O", "B-pro", "I-pro", "I-pro", "I-pro", "I-pro", "O", "O", "B-dis", "I-dis", "I-dis", "I-dis", "I-dis", "I-dis", "I-dis", "I-dis", "I-dis", "I-dis", "I-dis", "I-dis", "I-dis", "I-dis", "I-dis", "I-dis", "I-dis", "I-dis", "O", "B-pro", "I-pro", "I-pro", "I-pro", "O"]}

**Comment by lxbupt** [comment]
已解决，多谢

**Comment by Y-XS** [comment]
> 已解决，多谢

想问下什么问题，直接下载运行也报这个错json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Zhao11FF** [comment]
> 已解决，多谢

同问
