### ISSUE TITLE
运行完main.py后运行predict.py出现报错

### ISSUE THREAD

**Issue by okfmeplz** [taishan1994/BERT-BILSTM-CRF#46]
SyntaxError: Non-UTF-8 code starting with '\xe5' in file .........NER\BERT-BILSTM-CRF\predict.py on line 74, but no encoding declared

**Comment by taishan1994** [comment]
文件最开头加上# coding=utf-8

**Comment by okfmeplz** [comment]
谢谢大佬，我改过之后好像还报了不一样的：
Traceback (most recent call last):
  File "D\NER\BERT-BILSTM-CRF\predict.py", line 70, in <module>
    predictor = Predictor("dgre")
  File "D:\NER\BERT-BILSTM-CRF\predict.py", line 24, in __init__
    self.ner_args = get_args(os.path.join("./checkpoint/{}/".format(data_name), "ner_args.json"), "ner_args")
  File "D:\NER\BERT-BILSTM-CRF\predict.py", line 15, in get_args
    args_dict = json.load(fp)
  File "C:\ProgramData\anaconda3\envs\pytorch-gpu\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\ProgramData\anaconda3\envs\pytorch-gpu\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 180: invalid start byte
（TAT
