### ISSUE TITLE
你好，报这个错是什么原因

### ISSUE THREAD

**Issue by Angelucky** [taishan1994/BERT-BILSTM-CRF#47]
Traceback (most recent call last):
  File "/mnt/workspace/BERT-BILSTM-CRF/main.py", line 190, in <module>
    main(data_name)
  File "/mnt/workspace/BERT-BILSTM-CRF/main.py", line 182, in main
    train.train()
  File "/mnt/workspace/BERT-BILSTM-CRF/main.py", line 45, in train
    for step, batch_data in enumerate(self.train_loader):
  File "/mnt/workspace/BERT-BILSTM-CRF/env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/mnt/workspace/BERT-BILSTM-CRF/env/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/mnt/workspace/BERT-BILSTM-CRF/env/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/workspace/BERT-BILSTM-CRF/env/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/workspace/BERT-BILSTM-CRF/data_loader.py", line 28, in __getitem__
    labels = [self.label2id[label] for label in labels]
  File "/mnt/workspace/BERT-BILSTM-CRF/data_loader.py", line 28, in <listcomp>
    labels = [self.label2id[label] for label in labels]
KeyError: ''

**Comment by Angelucky** [comment]
是不是训练数据当中某一条数据里面没有标签，全是O的问题

**Comment by Angelucky** [comment]
数据格式这么可以吗
{"id": "2840", "text": ["山", "西", "省", "残", "联", "理", "事", "长", "苏", "高", "文", "说", "：", "“", "扶", "持", "残", "疾", "人", "解", "决", "温", "饱", "，", "不", "是", "残", "联", "一", "家", "的", "事", "情", "，", "而", "是", "由", "全", "社", "会", "共", "挑", "的", "担", "子", "。"], "labels": ["B-ORG", "I-ORG", "I-ORG", "I-ORG", "I-ORG", "O", "O", "O", "B-PER", "I-PER", "I-PER", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-ORG", "I-ORG", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]}

**Comment by taishan1994** [comment]
可以的

**Comment by Angelucky** [comment]
解决了，数据的问题，里面有空字符串""
